version: '3'
services: 
  web:
      build: .
      container_name: app
      expose: 
        - 8080
      working_dir: /app
      # command: ls
      command: bash -c "python manage.py makemigrations umbrella && python manage.py migrate && python manage.py runjobs minutely && gunicorn --workers=3 iclinic.wsgi -b 0.0.0.0:8080"

  nginx:
      restart: always
      build: ./nginx/      
      ports: 
        - "80:80"
      links:
        - web